### ISSUE TITLE
在使用请求信息时，只要需要Account的地方，全部无法正常发送请求。

### ISSUE THREAD

**Issue by yanguoshuai** [swtcpro/jingtum-lib-objectc#1]
你好，我在调用lib库的时候，发现只要需要调用“是否合法的地址”这个方法时，始终无法成功，请尽快解决，我的联系方式85275043@qq.com

**Comment by jerry20130912** [comment]
请参考 Attention 部分的说明，将  BTCBase58Alphabet 改成井通特有的字符串
